#!/usr/bin/env Rscript

# ==============================================================================
# ANR preliminary-data figure: DMD snRNA-seq + TF activity
#
# Panel A: real snRNA-seq UMAP from the Seurat object
# Panel B1: differential TF activity heatmap (DMD vs CTRL)
# Panel B2: focus on JUN/AP-1 activity across cell populations
#
# IMPORTANT:
# The TF activity results are donor-aware pseudobulk estimates generated by
# tf_activity_decoupler.R. Nuclei are therefore NOT treated as biological
# replicates in Panel B.
# ==============================================================================

# ------------------------------------------------------------------------------
# 0. PACKAGES
# ------------------------------------------------------------------------------

INSTALL_MISSING <- TRUE

cran_pkgs <- c(
  "Seurat",
  "dplyr",
  "ggplot2",
  "patchwork",
  "tibble",
  "svglite"
)

missing_cran <- cran_pkgs[
  !vapply(cran_pkgs, requireNamespace, logical(1), quietly = TRUE)
]

if (length(missing_cran) > 0) {
  if (!INSTALL_MISSING) {
    stop(
      "Missing CRAN packages: ",
      paste(missing_cran, collapse = ", ")
    )
  }

  install.packages(
    missing_cran,
    repos = "https://cloud.r-project.org"
  )
}

suppressPackageStartupMessages({
  library(Seurat)
  library(dplyr)
  library(ggplot2)
  library(patchwork)
})

# ------------------------------------------------------------------------------
# 1. CONFIG
# ------------------------------------------------------------------------------

RDS_PATH <- "data/Integration_paravertebral_final.rds"

TF_TABLE <- file.path(
  "results_tf_activity",
  "TF_activity",
  "all_celltypes_CollecTRI_ULM.tsv"
)

OUTDIR <- file.path(
  "results_tf_activity",
  "figures"
)

# Preferred UMAP reduction in the current object
REDUCTION <- "umap.rpca"

CELLTYPE_COL <- "cell_type"

# Main regulator to highlight.
# If JUN is absent, AP1 is used automatically.
TF_FOCUS_PREFERENCE <- c(
  "JUN",
  "AP1"
)

# Number of regulators in the discovery heatmap
TOP_N_TF <- 12

# Display only. Raw ULM scores are never modified in the result tables.
ACTIVITY_DISPLAY_LIMIT <- 4

# Cell-type order used in Panel B
CELLTYPE_ORDER <- c(
  "Myofibers",
  "Regenerating Myofibers",
  "Satellite cells",
  "FAPs",
  "Immune cells",
  "Endothelial",
  "Smooth muscle",
  "Tenocytes",
  "Schwann cells",
  "Neural cells",
  "Adipocytes"
)

# Consistent cell-type colors for the UMAP.
CELLTYPE_COLORS <- c(
  "Myofibers" = "#E76F51",
  "Regenerating Myofibers" = "#F28482",
  "Satellite cells" = "#59A14F",
  "FAPs" = "#4E79A7",
  "Immune cells" = "#F28E2B",
  "Endothelial" = "#76B7B2",
  "Smooth muscle" = "#B07AA1",
  "Tenocytes" = "#9C755F",
  "Schwann cells" = "#AF7AA1",
  "Neural cells" = "#8CD17D",
  "Adipocytes" = "#EDC948"
)

dir.create(
  OUTDIR,
  recursive = TRUE,
  showWarnings = FALSE
)

# ------------------------------------------------------------------------------
# 2. LOAD DATA
# ------------------------------------------------------------------------------

message("Reading Seurat object: ", RDS_PATH)
obj <- readRDS(RDS_PATH)

if (!inherits(obj, "Seurat")) {
  stop("RDS_PATH does not contain a Seurat object.")
}

if (!CELLTYPE_COL %in% colnames(obj@meta.data)) {
  stop(
    "Metadata column '",
    CELLTYPE_COL,
    "' not found."
  )
}

if (!file.exists(TF_TABLE)) {
  stop(
    "TF activity table not found: ",
    TF_TABLE,
    "\nRun tf_activity_decoupler.R first."
  )
}

tf_all <- read.delim(
  TF_TABLE,
  stringsAsFactors = FALSE,
  check.names = FALSE
) %>%
  dplyr::mutate(
    source = as.character(source),
    celltype = as.character(celltype),
    estimate = as.numeric(estimate),
    padj = as.numeric(padj)
  )

if (!all(c("source", "celltype", "estimate") %in% colnames(tf_all))) {
  stop(
    "TF_TABLE must contain source, celltype and estimate columns."
  )
}

# ------------------------------------------------------------------------------
# 3. PANEL A -- REAL UMAP
# ------------------------------------------------------------------------------

available_reductions <- Seurat::Reductions(obj)

if (!REDUCTION %in% available_reductions) {

  umap_candidates <- grep(
    "umap",
    available_reductions,
    value = TRUE,
    ignore.case = TRUE
  )

  if (length(umap_candidates) == 0) {
    stop(
      "No UMAP reduction found. Available reductions: ",
      paste(available_reductions, collapse = ", ")
    )
  }

  REDUCTION <- umap_candidates[[1]]

  message(
    "Requested UMAP not found; using: ",
    REDUCTION
  )
}

present_celltypes <- sort(
  unique(
    as.character(
      obj@meta.data[[CELLTYPE_COL]]
    )
  )
)

missing_colors <- setdiff(
  present_celltypes,
  names(CELLTYPE_COLORS)
)

if (length(missing_colors) > 0) {

  extra_cols <- grDevices::hcl.colors(
    length(missing_colors),
    palette = "Dark 3"
  )

  names(extra_cols) <- missing_colors

  CELLTYPE_COLORS <- c(
    CELLTYPE_COLORS,
    extra_cols
  )
}

p_umap <- Seurat::DimPlot(
  obj,
  reduction = REDUCTION,
  group.by = CELLTYPE_COL,
  cols = CELLTYPE_COLORS,
  label = TRUE,
  repel = TRUE,
  label.size = 3.2,
  pt.size = 0.12,
  raster = TRUE
) +
  Seurat::NoLegend() +
  ggplot2::labs(
    title = "A  Previous snRNA-seq analysis identifies\ncell populations in DMD muscle"
  ) +
  ggplot2::theme_classic(
    base_size = 9
  ) +
  ggplot2::theme(
    plot.title = ggplot2::element_text(
      face = "bold",
      size = 10.5,
      hjust = 0
    ),
    axis.title = ggplot2::element_text(
      size = 8.5
    ),
    axis.text = ggplot2::element_blank(),
    axis.ticks = ggplot2::element_blank(),
    plot.margin = ggplot2::margin(
      6, 8, 6, 6
    )
  )

# ------------------------------------------------------------------------------
# 4. PANEL B1 -- DIFFERENTIAL TF ACTIVITY HEATMAP
# ------------------------------------------------------------------------------

available_tfs <- unique(tf_all$source)

focus_tf <- TF_FOCUS_PREFERENCE[
  TF_FOCUS_PREFERENCE %in% available_tfs
][1]

if (length(focus_tf) == 0 || is.na(focus_tf)) {
  stop(
    "Neither JUN nor AP1 is present in the TF activity table."
  )
}

message(
  "Focused regulator: ",
  focus_tf
)

tf_rank <- tf_all %>%
  dplyr::filter(
    is.finite(estimate)
  ) %>%
  dplyr::group_by(source) %>%
  dplyr::summarise(
    max_abs_activity = max(
      abs(estimate),
      na.rm = TRUE
    ),
    .groups = "drop"
  ) %>%
  dplyr::arrange(
    dplyr::desc(max_abs_activity)
  )

top_tfs <- tf_rank %>%
  dplyr::slice_head(
    n = TOP_N_TF
  ) %>%
  dplyr::pull(source) %>%
  as.character()

# Force JUN/AP1 into the displayed set.
top_tfs <- unique(
  c(
    focus_tf,
    top_tfs
  )
)

top_tfs <- top_tfs[
  seq_len(
    min(
      TOP_N_TF,
      length(top_tfs)
    )
  )
]

celltype_order <- CELLTYPE_ORDER[
  CELLTYPE_ORDER %in% unique(tf_all$celltype)
]

extra_celltypes <- setdiff(
  unique(tf_all$celltype),
  celltype_order
)

celltype_order <- c(
  celltype_order,
  sort(extra_celltypes)
)

heat_df <- tf_all %>%
  dplyr::filter(
    source %in% top_tfs,
    celltype %in% celltype_order,
    is.finite(estimate)
  ) %>%
  dplyr::mutate(
    plot_estimate = pmax(
      -ACTIVITY_DISPLAY_LIMIT,
      pmin(
        ACTIVITY_DISPLAY_LIMIT,
        estimate
      )
    ),
    source = factor(
      source,
      levels = rev(top_tfs)
    ),
    celltype = factor(
      celltype,
      levels = celltype_order
    ),
    significant = !is.na(padj) & padj < 0.05
  )

p_heat <- ggplot2::ggplot(
  heat_df,
  ggplot2::aes(
    x = celltype,
    y = source,
    fill = plot_estimate
  )
) +
  ggplot2::geom_tile(
    color = "white",
    linewidth = 0.35
  ) +
  ggplot2::geom_point(
    data = heat_df %>%
      dplyr::filter(significant),
    shape = 8,
    size = 1.5,
    color = "black"
  ) +
  ggplot2::scale_fill_gradient2(
    low = "#2166AC",
    mid = "white",
    high = "#B2182B",
    midpoint = 0,
    limits = c(
      -ACTIVITY_DISPLAY_LIMIT,
      ACTIVITY_DISPLAY_LIMIT
    ),
    name = "ULM score"
  ) +
  ggplot2::labs(
    title = "Differential TF activity across cell populations",
    subtitle = "DMD vs CTRL | * adjusted P < 0.05",
    x = NULL,
    y = NULL
  ) +
  ggplot2::theme_minimal(
    base_size = 8.5
  ) +
  ggplot2::theme(
    plot.title = ggplot2::element_text(
      face = "bold",
      size = 9.5
    ),
    plot.subtitle = ggplot2::element_text(
      size = 7.5
    ),
    axis.text.x = ggplot2::element_text(
      angle = 40,
      hjust = 1,
      vjust = 1,
      size = 7.2
    ),
    axis.text.y = ggplot2::element_text(
      size = 7.5
    ),
    panel.grid = ggplot2::element_blank(),
    legend.position = "right",
    legend.title = ggplot2::element_text(
      size = 7.5
    ),
    legend.text = ggplot2::element_text(
      size = 7
    ),
    plot.margin = ggplot2::margin(
      3, 4, 3, 4
    )
  )

# ------------------------------------------------------------------------------
# 5. PANEL B2 -- FOCUS ON JUN / AP-1
# ------------------------------------------------------------------------------

focus_df <- tf_all %>%
  dplyr::filter(
    source == focus_tf,
    celltype %in% celltype_order,
    is.finite(estimate)
  ) %>%
  dplyr::mutate(
    celltype = factor(
      celltype,
      levels = rev(celltype_order)
    ),
    plot_estimate = pmax(
      -ACTIVITY_DISPLAY_LIMIT,
      pmin(
        ACTIVITY_DISPLAY_LIMIT,
        estimate
      )
    ),
    direction = ifelse(
      estimate >= 0,
      "Higher in DMD",
      "Lower in DMD"
    ),
    sig_label = dplyr::case_when(
      !is.na(padj) & padj < 0.001 ~ "***",
      !is.na(padj) & padj < 0.01 ~ "**",
      !is.na(padj) & padj < 0.05 ~ "*",
      TRUE ~ ""
    )
  )

p_focus <- ggplot2::ggplot(
  focus_df,
  ggplot2::aes(
    x = plot_estimate,
    y = celltype,
    fill = direction
  )
) +
  ggplot2::geom_col(
    width = 0.68
  ) +
  ggplot2::geom_vline(
    xintercept = 0,
    linewidth = 0.35,
    color = "grey30"
  ) +
  ggplot2::geom_text(
    ggplot2::aes(
      label = sig_label
    ),
    hjust = ifelse(
      focus_df$plot_estimate >= 0,
      -0.25,
      1.25
    ),
    size = 3
  ) +
  ggplot2::scale_fill_manual(
    values = c(
      "Higher in DMD" = "#B2182B",
      "Lower in DMD" = "#2166AC"
    ),
    name = NULL
  ) +
  ggplot2::coord_cartesian(
    xlim = c(
      -ACTIVITY_DISPLAY_LIMIT - 0.35,
      ACTIVITY_DISPLAY_LIMIT + 0.35
    ),
    clip = "off"
  ) +
  ggplot2::labs(
    title = paste0(
      focus_tf,
      " / AP-1 differential activity"
    ),
    subtitle = "Positive = higher inferred activity in DMD",
    x = "ULM activity score (DMD vs CTRL)",
    y = NULL
  ) +
  ggplot2::theme_classic(
    base_size = 8.5
  ) +
  ggplot2::theme(
    plot.title = ggplot2::element_text(
      face = "bold",
      size = 9.5
    ),
    plot.subtitle = ggplot2::element_text(
      size = 7.5
    ),
    axis.text.y = ggplot2::element_text(
      size = 7.2
    ),
    axis.text.x = ggplot2::element_text(
      size = 7
    ),
    axis.title.x = ggplot2::element_text(
      size = 7.5
    ),
    legend.position = "bottom",
    legend.text = ggplot2::element_text(
      size = 7.2
    ),
    plot.margin = ggplot2::margin(
      3, 10, 3, 4
    )
  )

# ------------------------------------------------------------------------------
# 6. ASSEMBLE PANEL B AND FINAL FIGURE
# ------------------------------------------------------------------------------

panel_b <- (
  p_heat /
    p_focus
) +
  patchwork::plot_layout(
    heights = c(
      1.15,
      0.85
    )
  ) +
  patchwork::plot_annotation(
    title = "B  Preliminary analyses identify AP-1/JUN as a candidate regulator",
    theme = ggplot2::theme(
      plot.title = ggplot2::element_text(
        face = "bold",
        size = 10.5,
        hjust = 0
      )
    )
  )

final_plot <- (
  p_umap |
    panel_b
) +
  patchwork::plot_layout(
    widths = c(
      0.95,
      1.45
    )
  ) &
  ggplot2::theme(
    plot.background = ggplot2::element_rect(
      fill = "white",
      color = NA
    )
  )

# ------------------------------------------------------------------------------
# 7. EXPORT
# ------------------------------------------------------------------------------

base_name <- file.path(
  OUTDIR,
  "ANR_preliminary_snRNAseq_TF_activity"
)

ggplot2::ggsave(
  paste0(
    base_name,
    ".pdf"
  ),
  final_plot,
  width = 12.2,
  height = 5.2,
  units = "in"
)

ggplot2::ggsave(
  paste0(
    base_name,
    ".png"
  ),
  final_plot,
  width = 12.2,
  height = 5.2,
  units = "in",
  dpi = 400,
  bg = "white"
)

ggplot2::ggsave(
  paste0(
    base_name,
    ".svg"
  ),
  final_plot,
  width = 12.2,
  height = 5.2,
  units = "in",
  device = svglite::svglite
)

message(
  "ANR figure written to: ",
  normalizePath(OUTDIR)
)
